### ISSUE TITLE
ibuffer-current-state-list: Args out of range: #<buffer *Ibuffer*>, 207, 259

### ISSUE THREAD

**Issue by wdenton** [purcell/ibuffer-vc#19] opened 2016-12-21 13:10 UTC
ibuffer-vc stopped working very recently and throws this error when I run it.  Instead of showing all the buffers I have in their various projects and source trees, it just shows two or three under Default. 

Running `emacs -Q` and loading in the package shows no problem.

This is on Emacs 26.0.50.20, compiled from the development source in Git. I see no changes have been made to this code recently, so perhaps there's some conflict somewhere else?

**Comment by purcell** [comment] 2016-12-24 08:44
This is likely due to an out-of-date `ibuffer-vc.elc` file. Or simply a bug in `ibuffer` in that development version of Emacs.

**Comment by Chream** [comment] 2017-03-13 03:20
I have the same. 

ibuffer-vc version: Package-Version: 20161103.2358
emacs version: 26.0.50.1

**Comment by purcell** [comment] 2017-03-13 08:20
Yep, okay. So have you recompiled `ibuffer-vc.el` since upgrading your Emacs? I don't see that there's anything that could need to be fixed in `ibuffer-vc`, so my previous comment stands unless someone can investigate and tell me otherwise. :-)

**Comment by johnmastro** [comment] 2017-03-28 23:15
I ran into this too. I haven't had a chance to investigate much and find out what changed, but it appears to be caused by a bug (or just incompatibility) in Emacs 26's `ibuffer`.

I'll see about submitting a patch to `ibuffer`. In the meantime I found a workaround that seems to work, at least so far:

```emacs-lisp
(defun ibuffer-vc--status-string-no-nil (result)
  "Advice for `ibuffer-vc--status-string'. Don't return nil."
  (or result ""))

(advice-add 'ibuffer-vc--status-string :filter-return
            #'ibuffer-vc--status-string-no-nil)
```

(Replacing the definition of `ibuffer-vc--status-string` to return the empty string rather than `nil` also works, but since I suspect this is something that can/should be addressed in `ibuffer` itself I'm  just using this as a bandaid).

**Comment by johnmastro** [comment] 2017-03-30 23:18
I've now submitted a [patch](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=26317) to Emacs that I believe fixes this.

If you read the bug report, you may notice that I mention a "wrong type argument" error, whereas this thread mentions an "args out of range" error. I believe they have the same cause. In my testing, the "wrong type argument" happened the first time `ibuffer` was invoked, followed by "args out of range" for any subsequent invocations (unless you explicitly killed the `*Ibuffer*` buffer, in which case it would go back to the "wrong type argumen" error on the first call after that).

**Comment by johnmastro** [comment] 2017-03-31 00:32
The patch I proposed has been [applied](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=eeaa707eb6c437b4a23d353eca5de1dc21bf7b24) in Emacs's master branch.

**Comment by purcell** [comment] 2017-03-31 22:26
Nice work @johnmastro! I'll go ahead and close this issue.

**Closed by purcell** 2017-03-31 22:26 UTC
